server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/api/books/**

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**

        - id: loan-service
          uri: http://loan-service:8083
          predicates:
            - Path=/api/loans/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
