server:
  port: 8081

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      # Permite conexiones desde fuera del contenedor de Docker
      settings:
        web-allow-others: true